<?php
$i = 0;
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_INDEX;
$adminmenu[$i]['link'] = "admin/index.php";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_LOCATIONCATEGORY;
$adminmenu[$i]['link'] = "admin/locationcategory.php";
$adminmenu[$i]['icon'] = "images/icons/folder_map.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_LOCATION;
$adminmenu[$i]['link'] = "admin/location.php";
$adminmenu[$i]['icon'] = "images/icons/map.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_LOCATIONPERMISSIONS;
$adminmenu[$i]['link'] = "admin/locationpermissions.php";
$adminmenu[$i]['icon'] = "images/icons/lock_map.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_FIELDCATEGORY;
$adminmenu[$i]['link'] = "admin/fieldcategory.php";
$adminmenu[$i]['icon'] = "images/icons/folder_database.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_FIELD;
$adminmenu[$i]['link'] = "admin/field.php";
$adminmenu[$i]['icon'] = "images/icons/database.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_FIELDPERMISSIONS;
$adminmenu[$i]['link'] = "admin/fieldpermissions.php";
$adminmenu[$i]['icon'] = "images/icons/lock_database.png";
$i++;
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_ABOUT;
$adminmenu[$i]['link'] = "admin/about.php";
$adminmenu[$i]['icon'] = "images/icons/information.png";
//$i++;
//$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_UPDATE;
//$adminmenu[$i]['link'] = "../system/admin.php?fct=modulesadmin&op=update&module=xaddresses";
//$adminmenu[$i]['icon'] = "images/icons/update.png";
//$i++;
//$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU10;
//$adminmenu[$i]['link'] = "admin/import.php";
//$adminmenu[$i]['icon'] = "images/icons/folder_put.png";
?>