<?php
$adminmenu = array();
$i = 0;
$i++;
$adminmenu[$i]['name'] = 'Index';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_INDEX;
$adminmenu[$i]['link'] = "admin/index.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_INDEX_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/house.png";
$i++;
$adminmenu[$i]['name'] = 'Locationcategory';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_ITEMCATEGORY;
$adminmenu[$i]['link'] = "admin/locationcategory.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_ITEMCATEGORY_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/folder_map.png";
$i++;
$adminmenu[$i]['name'] = 'Location';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_ITEM;
$adminmenu[$i]['link'] = "admin/location.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_ITEM_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/map.png";
$i++;
$adminmenu[$i]['name'] = 'Fieldcategory';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_FIELDCATEGORY;
$adminmenu[$i]['link'] = "admin/fieldcategory.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_FIELDCATEGORY_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/folder_database.png";
$i++;
$adminmenu[$i]['name'] = 'Field';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_FIELD;
$adminmenu[$i]['link'] = "admin/field.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_FIELD_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/database.png";
$i++;
$adminmenu[$i]['name'] = 'Permissions';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_PERMISSIONS;
$adminmenu[$i]['link'] = "admin/permissions.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_PERMISSIONS_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/lock.png";
$i++;
$adminmenu[$i]['name'] = 'Import';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_IMPORT;
$adminmenu[$i]['link'] = "admin/import.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_IMPORT_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/folder_put.png";
$i++;
$adminmenu[$i]['name'] = 'About';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_ABOUT;
$adminmenu[$i]['link'] = "admin/about.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_ABOUT_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/information.png";
$i++;
$adminmenu[$i]['name'] = 'Help';
$adminmenu[$i]['title'] = _XADDRESSES_MI_ADMENU_HELP;
$adminmenu[$i]['link'] = "admin/help.php";
$adminmenu[$i]['desc'] = _XADDRESSES_MI_ADMENU_HELP_DESC;
$adminmenu[$i]['icon'] = "images/icons/32x32/help.png";
?>